# Generated by Django 5.2.1 on 2025-05-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented'), ('reserved', 'Reserved')], default='available', max_length=20, verbose_name='Estado'),
        ),
    ]
